default_context:
  project_name: 'sep_coursework'
  project_slug: 'sep_coursework'
  domain_main: 'sep_coursework.com'
  domain_staging: 'stag.sep_coursework.com'
  docker_swarm_stack_name_main: 'sep_coursework-com'
  docker_swarm_stack_name_staging: 'stag-sep_coursework-com'
  secret_key: 'changethis'
  first_superuser: 'admin@sep_coursework.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.mtaa_coursework.com", "https://stag.mtaa_coursework.com", "https://mtaa_coursework.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@sep_coursework.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@sep_coursework.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'sep_coursework.com'
  traefik_constraint_tag_staging: 'stag.sep_coursework.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
